import { useState } from "react";
import { ArrowLeft, CheckCircle2, FileSearch, Loader2, PauseCircle, PlayCircle, ShieldCheck } from "lucide-react";
import { useLocation } from "wouter";
import { trpc } from "@/lib/trpc";
import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";

export default function ApertureDisclosure() {
  const [, navigate] = useLocation(); const utils = trpc.useUtils();
  const [intent, setIntent] = useState("Review House Clerk public filings weekly for liquid, exactly-resolved equities and ETFs. Hold every ambiguous asset for manual evidence review.");
  const [draft, setDraft] = useState<{ unresolved: string[]; confidenceNotes: string[] } | null>(null);
  const [selectedPlanId, setSelectedPlanId] = useState<number | null>(null);
  const { data: plans, isLoading } = trpc.aperture.disclosure.plan.list.useQuery();
  const activePlanId = selectedPlanId ?? plans?.[0]?.id ?? null;
  const { data: matches } = trpc.aperture.disclosure.match.list.useQuery({ planId: activePlanId ?? 0 }, { enabled: activePlanId !== null });
  const compile = trpc.aperture.disclosure.compileIntent.useMutation({ onSuccess: (result) => setDraft(result), onError: (error) => toast.error(error.message) });
  const createRevision = trpc.aperture.disclosure.plan.createRevision.useMutation({ onSuccess: (result) => { setDraft(result.compiledPlan); utils.aperture.disclosure.plan.list.invalidate(); toast.success(`Revision ${result.revisionNumber} is ready for review`); }, onError: (error) => toast.error(error.message) });
  const approve = trpc.aperture.disclosure.plan.approveRevision.useMutation({ onSuccess: () => { utils.aperture.disclosure.plan.list.invalidate(); toast.success("Monitoring approved. Source retrieval remains evidence-only."); }, onError: (error) => toast.error(error.message) });
  const pause = trpc.aperture.disclosure.plan.pause.useMutation({ onSuccess: () => { utils.aperture.disclosure.plan.list.invalidate(); toast.success("Plan paused; its history remains intact."); } });
  const replay = trpc.aperture.disclosure.replayOfficialFixture.useMutation({ onSuccess: (result) => toast.success(`Official fixture replayed: ${result.observations.length} observation(s), no broker order.`), onError: (error) => toast.error(error.message) });
  const promote = trpc.aperture.disclosure.match.promoteEvidence.useMutation({ onSuccess: () => { utils.aperture.disclosure.match.list.invalidate(); toast.success("Cited evidence promoted. Paper recipe readiness remains a separate gate."); }, onError: (error) => toast.error(error.message) });

  return <DashboardLayout><main className="mx-auto max-w-5xl space-y-6">
    <header className="flex items-start gap-3"><Button variant="ghost" size="icon" aria-label="Back to Capital decision center" onClick={() => navigate("/aperture")}><ArrowLeft className="h-4 w-4" /></Button><div><p className="text-[0.68rem] font-semibold uppercase tracking-[0.14em]" style={{ color: "var(--sh-signal)" }}>Capital Operator · disclosure intelligence</p><h1 className="mt-1 font-serif text-3xl" style={{ color: "var(--sh-text-primary)" }}>Disclosure plans</h1><p className="mt-2 max-w-3xl text-sm leading-6" style={{ color: "var(--sh-fg-muted)" }}>Orient to a public filing source, choose a bounded evidence question, verify source conditions, then stage research or decline. This rail does not rank filers, predict returns, or create broker orders.</p></div></header>
    <section className="grid gap-px overflow-hidden rounded-xl border md:grid-cols-3" style={{ borderColor: "var(--sh-border-1)", background: "var(--sh-border-1)" }}><div className="p-4" style={{ background: "var(--sh-surface-2)" }}><p className="text-xs font-semibold uppercase tracking-wide" style={{ color: "var(--sh-fg-muted)" }}>Source</p><p className="mt-1 font-semibold" style={{ color: "var(--sh-text-primary)" }}>House Clerk only</p></div><div className="p-4" style={{ background: "var(--sh-surface-2)" }}><p className="text-xs font-semibold uppercase tracking-wide" style={{ color: "var(--sh-fg-muted)" }}>Mandate</p><p className="mt-1 font-semibold" style={{ color: "var(--sh-text-primary)" }}>45-day lag · $15,001 floor</p></div><div className="p-4" style={{ background: "var(--sh-surface-2)" }}><p className="text-xs font-semibold uppercase tracking-wide" style={{ color: "var(--sh-fg-muted)" }}>Boundary</p><p className="mt-1 font-semibold" style={{ color: "var(--sh-text-primary)" }}>Evidence first · paper gates separate</p></div></section>
    <Card style={{ background: "var(--sh-surface-2)", borderColor: "var(--sh-border-1)" }}><CardContent className="space-y-4 pt-5"><div><p className="font-semibold" style={{ color: "var(--sh-text-primary)" }}>1. Describe one monitoring decision</p><p className="mt-1 text-sm" style={{ color: "var(--sh-fg-muted)" }}>Ambiguities remain visible and block approval; they are never silently filled in.</p></div><Textarea value={intent} onChange={(event) => setIntent(event.target.value)} className="min-h-28" aria-label="Disclosure monitoring intent" />{draft && <div className="rounded-lg border p-3 text-sm" style={{ borderColor: draft.unresolved.length ? "var(--sh-orange)" : "var(--sh-border-1)" }}><p className="font-medium" style={{ color: "var(--sh-text-primary)" }}>{draft.unresolved.length ? "Approval blockers" : "Ready for immutable revision"}</p>{draft.unresolved.length ? <ul className="mt-2 list-disc space-y-1 pl-5" style={{ color: "var(--sh-fg-muted)" }}>{draft.unresolved.map((item) => <li key={item}>{item}</li>)}</ul> : <p className="mt-1" style={{ color: "var(--sh-fg-muted)" }}>The plan may be saved as a revision and explicitly approved before any source replay.</p>}</div>}<div className="flex flex-wrap gap-2"><Button variant="outline" disabled={compile.isPending} onClick={() => compile.mutate({ rawIntent: intent })}>{compile.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <FileSearch className="mr-2 h-4 w-4" />}Compile plan</Button><Button disabled={!draft || draft.unresolved.length > 0 || createRevision.isPending} onClick={() => createRevision.mutate({ rawIntent: intent })}><ShieldCheck className="mr-2 h-4 w-4" />Save immutable revision</Button></div></CardContent></Card>
    <section className="space-y-3"><h2 className="font-serif text-2xl" style={{ color: "var(--sh-text-primary)" }}>2. Review, approve, or pause</h2>{isLoading ? <p className="text-sm" style={{ color: "var(--sh-fg-muted)" }}>Loading your plans…</p> : !plans?.length ? <p className="rounded-lg border p-4 text-sm" style={{ borderColor: "var(--sh-border-1)", color: "var(--sh-fg-muted)" }}>No disclosure plan exists yet. Compile one bounded monitoring request above.</p> : plans.map((plan) => <Card key={plan.id} onClick={() => setSelectedPlanId(plan.id)} className="cursor-pointer" style={{ background: "var(--sh-surface-2)", borderColor: activePlanId === plan.id ? "var(--sh-signal)" : "var(--sh-border-1)" }}><CardContent className="flex flex-col gap-3 pt-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold" style={{ color: "var(--sh-text-primary)" }}>Plan #{plan.id} · {plan.status}</p><p className="mt-1 text-sm" style={{ color: "var(--sh-fg-muted)" }}>Revision {plan.currentRevisionId ?? "not saved"} · history is immutable and owner-scoped.</p></div><div className="flex flex-wrap gap-2">{plan.status === "review" && plan.currentRevisionId !== null && <Button size="sm" onClick={(event) => { event.stopPropagation(); approve.mutate({ planId: plan.id, revisionId: Number(plan.currentRevisionId) }); }}><CheckCircle2 className="mr-1.5 h-3.5 w-3.5" />Approve monitoring</Button>}{plan.status === "monitoring" && <><Button size="sm" variant="outline" onClick={(event) => { event.stopPropagation(); replay.mutate({ planId: plan.id }); }}><PlayCircle className="mr-1.5 h-3.5 w-3.5" />Replay official fixture</Button><Button size="sm" variant="outline" onClick={(event) => { event.stopPropagation(); pause.mutate({ planId: plan.id }); }}><PauseCircle className="mr-1.5 h-3.5 w-3.5" />Pause</Button></>}</div></CardContent></Card>)}</section>
    <section className="space-y-3"><h2 className="font-serif text-2xl" style={{ color: "var(--sh-text-primary)" }}>3. Verify source conditions</h2><p className="max-w-3xl text-sm leading-6" style={{ color: "var(--sh-fg-muted)" }}>Observations retain the original raw asset text, disclosed range, receipt timing, source link, and every gate reason. An exact entity match is required before cited evidence can move forward; nothing here creates a trade.</p>{!activePlanId ? <p className="rounded-lg border p-4 text-sm" style={{ borderColor: "var(--sh-border-1)", color: "var(--sh-fg-muted)" }}>Choose an approved monitoring plan to inspect its evidence queue.</p> : !matches?.length ? <p className="rounded-lg border p-4 text-sm" style={{ borderColor: "var(--sh-border-1)", color: "var(--sh-fg-muted)" }}>No observations yet. Replay the frozen official House Clerk fixture from an approved plan to validate the provenance chain.</p> : <div className="space-y-3">{matches.map(({ match, transaction, filing }) => <Card key={match.id} style={{ background: "var(--sh-surface-2)", borderColor: match.state === "reviewable" ? "var(--sh-signal)" : "var(--sh-border-1)" }}><CardContent className="space-y-3 pt-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold" style={{ color: "var(--sh-text-primary)" }}>{transaction.rawAssetName}</p><p className="mt-1 text-xs" style={{ color: "var(--sh-fg-muted)" }}>{transaction.ownerAsStated} · {transaction.transactionType} · disclosed ${transaction.amountMinUsd?.toLocaleString() ?? "—"}–${transaction.amountMaxUsd?.toLocaleString() ?? "—"}</p></div><span className="rounded-full border px-2 py-1 text-xs font-semibold" style={{ borderColor: "var(--sh-border-1)", color: "var(--sh-text-primary)" }}>{match.state}</span></div><p className="text-xs leading-5" style={{ color: "var(--sh-fg-muted)" }}>Source: <a className="underline" href={filing.canonicalUrl} target="_blank" rel="noreferrer">House Clerk filing {filing.stableSourceDocumentId}</a> · eligible {transaction.eligibleFrom ? new Date(transaction.eligibleFrom).toLocaleDateString() : "not measurable"}</p>{Array.isArray(match.reasons) && match.reasons.length > 0 && <p className="rounded-md border px-3 py-2 text-xs" style={{ borderColor: "var(--sh-border-1)", color: "var(--sh-fg-muted)" }}>Held because: {(match.reasons as string[]).join(" · ")}</p>}{match.state === "reviewable" && <Button size="sm" onClick={() => promote.mutate({ matchId: match.id, note: "Operator reviewed source-provenance and mandate gates; promoted as cited research evidence only." })}>Promote cited evidence</Button>}</CardContent></Card>)}</div>}</section>
  </main></DashboardLayout>;
}
