import { Link, useLocation } from "wouter";
import { AlertTriangle, ArrowLeft, CircleDotDashed, Clock3, LockKeyhole, ShieldAlert } from "lucide-react";
import { Button } from "@/components/ui/button";
import { CAPITAL_WALKTHROUGH_FIXTURES } from "@/fixtures/capitalWalkthroughFixtures";
import { CAPITAL_WALKTHROUGH_DISCLOSURE, type CapitalWalkthroughFixture } from "@shared/capitalWalkthrough";

const CONSTRUCTED_PLAY_DISCLOSURE = "Levels are modeled from observed minute bars under the assumptions listed with them, not quoted from a source and not a recommendation. Confirm every level against a real-time terminal before acting. This is a paper research proposal: it creates no order, and a human must review, acknowledge and approve it separately.";
const STEPS = ["Today", "Rail", "One play", "Trigger", "Evidence", "Refusal", "Record"] as const;
const FRESHNESS_WINDOW_MS = 24 * 60 * 60 * 1000;

const money = (value: unknown) => typeof value === "number"
  ? new Intl.NumberFormat(undefined, { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value / 100)
  : "Not measured";
const timestamp = (value: number | null | undefined) => value == null
  ? "Not measured"
  : new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));

function JsonFact({ label, value }: { label: string; value: unknown }) {
  const text = typeof value === "string" || typeof value === "number" || typeof value === "boolean" ? String(value) : JSON.stringify(value, null, 2);
  return <div className="rounded-lg border border-rule bg-paper p-3"><p className="font-eyebrow text-eyebrow text-muted-foreground">{label}</p><pre className="mt-1 overflow-x-auto whitespace-pre-wrap break-words font-mono text-xs leading-5 text-ink">{text}</pre></div>;
}

function CaptureProvenance({ capturedAt, source }: { capturedAt?: number; source?: string }) {
  if (capturedAt == null && !source) return <p className="text-xs text-ink/60">Legacy fixture: this field predates structured source metadata.</p>;
  return <p className="text-xs leading-5 text-ink/60">Captured {timestamp(capturedAt)}{source ? ` · source: ${source}` : ""}</p>;
}

function ReplayStep({ fixture, step }: { fixture: CapitalWalkthroughFixture; step: number }) {
  if (step === 1) return <div className="space-y-4"><div className="rounded-lg border border-amber bg-amber/5 p-4"><p className="font-medium text-ink">Cash is preserved as an explicit outcome</p><p className="mt-1 text-sm leading-6 text-ink/75">{fixture.today.cashOutcome}</p></div><div className="grid gap-3 sm:grid-cols-2"><JsonFact label="Queue ordering" value={fixture.today.queueOrderingBasis} /><JsonFact label="Expired-catalyst count" value={fixture.today.expiredPlayCount ?? fixture.today.expiredPlayBasis} /></div><CaptureProvenance capturedAt={fixture.today.capturedAt} source={fixture.today.source} /><div className="space-y-2">{fixture.queue.map((play, index) => <div key={play.symbol} className={`rounded-lg border p-3 ${play.symbol === fixture.selectedPlay.symbol ? "border-amber bg-amber/5" : "border-rule bg-paper"}`}><div className="flex items-start justify-between gap-3"><div><p className="font-medium text-ink">{index + 1}. {play.symbol}{play.company ? ` · ${play.company}` : ""}</p><p className="mt-1 text-xs leading-5 text-ink/70">{play.evidenceSummary}</p></div><span className="font-mono text-xs text-muted-foreground">{play.playSide ?? "direction not measured"}</span></div></div>)}</div></div>;
  if (step === 2) return <div className="space-y-3"><div className="grid gap-3 sm:grid-cols-2"><JsonFact label="Market session at capture" value={`${fixture.rail.marketSession} · ${fixture.rail.marketSessionBasis}`} /><JsonFact label="Paper account and staleness" value={`${fixture.source.accountLabel} · last synced ${timestamp(fixture.account.lastSyncedAt)}`} /><JsonFact label="Mandate" value={fixture.rail.mandateVersion} /><JsonFact label="Tightest measured constraint" value={`${fixture.rail.tightestConstraint} · ${fixture.rail.tightestConstraintBasis}`} /></div><JsonFact label="Captured headroom" value={fixture.rail.headroom} /><CaptureProvenance capturedAt={fixture.rail.capturedAt} source={fixture.rail.source} /></div>;
  if (step === 3) return <div className="space-y-3"><div className="rounded-lg border border-amber bg-amber/5 p-4"><p className="font-medium text-ink">Modeled recipe—confirm before any action</p><p className="mt-1 text-sm leading-6 text-ink/75">{CONSTRUCTED_PLAY_DISCLOSURE}</p></div><JsonFact label="Captured constructed recipe" value={fixture.recipe} /></div>;
  if (step === 4) return <div className="space-y-3"><div className="flex gap-3 rounded-lg border border-amber bg-amber/5 p-4"><CircleDotDashed className="mt-0.5 h-5 w-5 shrink-0 text-amber"/><div><p className="font-medium text-ink">Trigger state preserved as captured</p><p className="mt-1 text-sm leading-6 text-ink/75">The replay does not refresh tape. An unknown state is a task for the operator’s terminal, not a UI error to optimize away.</p></div></div><JsonFact label="Captured trigger, feed, and lag" value={fixture.trigger} /></div>;
  if (step === 5) return <div className="space-y-3"><JsonFact label="Evidence checked in source run" value={fixture.evidence.verifiedFields} /><div className="rounded-lg border border-rule bg-paper p-4"><p className="font-medium text-ink">Set-aside record</p><p className="mt-1 text-sm leading-6 text-ink/75">{fixture.evidence.setAsideBasis}</p>{fixture.evidence.setAside.length > 0 ? <div className="mt-3 space-y-2">{fixture.evidence.setAside.map((item) => <JsonFact key={`${item.symbol}-${item.reason}`} label={item.symbol} value={item.reason} />)}</div> : <p className="mt-3 text-xs text-ink/60">No documented exclusions were persisted for this capture.</p>}<div className="mt-3"><CaptureProvenance capturedAt={fixture.evidence.capturedAt} source={fixture.evidence.source} /></div></div></div>;
  if (step === 6) return <div className="grid gap-3 lg:grid-cols-2"><div className="rounded-lg border border-clay/45 bg-clay/5 p-4"><div className="flex gap-2"><ShieldAlert className="h-5 w-5 text-clay"/><div><p className="font-medium text-ink">Open-intent preflight remains blocked</p><p className="mt-1 text-xs text-ink/70">Incomplete tape and measured-risk fields prevented a proposal. No order was created.</p></div></div><div className="mt-3"><JsonFact label="Captured open-intent preflight" value={fixture.proposal.allowed} /></div></div><div className="rounded-lg border border-clay/45 bg-clay/5 p-4"><div className="flex gap-2"><ShieldAlert className="h-5 w-5 text-clay"/><div><p className="font-medium text-ink">Close-intent refusal preserved</p><p className="mt-1 text-xs text-ink/70">{fixture.proposal.refusalReason}</p></div></div><div className="mt-3"><JsonFact label="Captured refused close-intent preflight" value={fixture.proposal.refused} /></div></div></div>;
  return <div className="space-y-3"><div className="rounded-lg border border-rule bg-paper p-4"><p className="font-medium text-ink">Outcome ledger</p><p className="mt-1 text-sm leading-6 text-ink/75">{fixture.outcome.captured ? "The source-timed result below is preserved exactly as captured." : fixture.outcome.absentReason ?? "Not measured."}</p></div><JsonFact label="Captured paper outcome" value={fixture.outcome.captured ?? "Not measured — no outcome row was captured."} /><CaptureProvenance capturedAt={fixture.outcome.capturedAt} source={fixture.outcome.source} /><p className="rounded-lg border border-amber bg-amber/5 p-4 text-sm leading-6 text-ink">{fixture.outcome.sampleSufficiency}</p></div>;
}

export default function CapitalWalkthrough() {
  const [location, navigate] = useLocation();
  const query = new URLSearchParams(typeof window === "undefined" ? location.split("?")[1] ?? "" : window.location.search);
  const fixture = CAPITAL_WALKTHROUGH_FIXTURES.find((item) => item.version === query.get("capture")) ?? CAPITAL_WALKTHROUGH_FIXTURES[0] ?? null;
  const requestedStep = Number(query.get("step") ?? "1");
  const step = Number.isInteger(requestedStep) && requestedStep >= 1 && requestedStep <= STEPS.length ? requestedStep : 1;
  const select = (nextFixture: CapitalWalkthroughFixture, nextStep = step) => navigate(`/aperture/walkthrough?capture=${encodeURIComponent(nextFixture.version)}&step=${nextStep}`);
  if (!fixture) return <main className="min-h-screen bg-bone p-6 text-ink"><section className="mx-auto max-w-3xl rounded-xl border border-dashed border-rule bg-paper p-8 text-center"><AlertTriangle className="mx-auto h-7 w-7 text-amber"/><h1 className="mt-3 font-display text-2xl">No captured replay is loaded</h1><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-ink/70">A demo is never synthesized. Add a versioned real-session fixture before using this route.</p></section></main>;
  const olderThanWindow = Math.max(0, Date.now() - fixture.capturedAt) > FRESHNESS_WINDOW_MS;
  return <main className="min-h-screen bg-bone text-ink"><div className="mx-auto max-w-5xl px-4 py-6 sm:px-6 sm:py-10">
    <Link href="/aperture" className="inline-flex items-center gap-1 text-sm text-amber hover:underline"><ArrowLeft className="h-4 w-4" /> Decision Center</Link>
    <header className="mt-5 border-b border-rule pb-5"><div className="flex flex-wrap items-center gap-2"><span className="font-eyebrow text-eyebrow text-amber">Capital Aperture</span><span className="inline-flex items-center gap-1 rounded-full border border-rule bg-paper px-2 py-1 font-mono text-[10px] text-ink/70"><LockKeyhole className="h-3 w-3" /> Admin-only frozen replay</span></div><h1 className="mt-3 font-display text-3xl text-ink sm:text-4xl">Paper session walkthrough</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-ink/75">{CAPITAL_WALKTHROUGH_DISCLOSURE}</p></header>
    <section className="sticky top-0 z-10 mt-4 rounded-xl border border-amber bg-amber/10 p-4 shadow-sm"><div className="flex gap-3"><Clock3 className="mt-0.5 h-5 w-5 shrink-0 text-amber"/><div><p className="font-medium text-ink">Recorded session — {timestamp(fixture.capturedAt)}. Every figure was true at capture.</p><p className="mt-1 text-sm leading-6 text-ink/75">Nothing here is live and no order can be created from this page. {olderThanWindow ? "This recording is older than the 24-hour freshness window; it remains a historical replay." : "This recording is within the stated 24-hour freshness window."}</p></div></div></section>
    <section className="mt-4 grid gap-3 rounded-xl border border-rule bg-paper p-4 sm:grid-cols-[1fr_auto]"><div><p className="font-eyebrow text-eyebrow text-muted-foreground">Capture index</p><label className="mt-1 block text-sm text-ink" htmlFor="capture-version">Choose a recorded version</label><select id="capture-version" className="mt-1 w-full rounded-md border border-rule bg-bone p-2 text-sm text-ink" value={fixture.version} onChange={(event) => { const next = CAPITAL_WALKTHROUGH_FIXTURES.find((item) => item.version === event.target.value); if (next) select(next, 1); }}>{CAPITAL_WALKTHROUGH_FIXTURES.map((item) => <option key={item.version} value={item.version}>{item.version} · {timestamp(item.capturedAt)}</option>)}</select></div><div className="self-end font-mono text-xs text-ink/60">Run #{fixture.source.runId}<br />{fixture.source.accountLabel}</div></section>
    <nav className="mt-4 flex flex-wrap gap-2" aria-label="Walkthrough steps">{STEPS.map((label, index) => <Button key={label} onClick={() => select(fixture, index + 1)} variant={step === index + 1 ? "default" : "outline"} size="sm">{index + 1} · {label}</Button>)}</nav>
    <section className="mt-4 min-h-[360px] rounded-xl border border-rule bg-bone p-4 sm:p-6"><ReplayStep fixture={fixture} step={step} /></section>
    <footer className="mt-6 text-xs leading-5 text-ink/55">The walkthrough imports a static versioned fixture. It has no tRPC hook, fetch, broker adapter, provider call, database read, or write control.</footer>
  </div></main>;
}
