CREATE TABLE `demo_scenarios` (
	`id` int AUTO_INCREMENT NOT NULL,
	`thesis_title` varchar(256) NOT NULL,
	`thesis_summary` text,
	`deal_id` int,
	`business_name` varchar(256) NOT NULL,
	`industry` varchar(128),
	`location` varchar(256),
	`revenue` bigint,
	`cash_flow` bigint,
	`asking_price` bigint,
	`multiple` float,
	`employees` int,
	`year_established` int,
	`score` float,
	`score_breakdown` json,
	`signals` json,
	`ic_summary` text,
	`investment_thesis` text,
	`key_risks` json,
	`catalysts` json,
	`snapshot_at` timestamp NOT NULL DEFAULT (now()),
	`data_sources_used` json,
	`is_active` boolean NOT NULL DEFAULT true,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `demo_scenarios_id` PRIMARY KEY(`id`)
);
