CREATE TABLE aperture_play_slates (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  canonical_thesis_id INT NULL,
  account_id INT NULL,
  session_date_et VARCHAR(10) NOT NULL,
  window_key VARCHAR(64) NOT NULL DEFAULT 'opening',
  snapshot_basis ENUM('live_capture', 'historical_reconstruction') NOT NULL DEFAULT 'live_capture',
  status ENUM('captured', 'awaiting_outcome', 'complete') NOT NULL DEFAULT 'captured',
  operator_decision ENUM('not_recorded', 'cash', 'selected') NOT NULL DEFAULT 'not_recorded',
  operator_reason TEXT NULL,
  decided_at BIGINT NULL,
  portfolio_snapshot JSON NOT NULL,
  context_snapshot JSON NOT NULL,
  captured_at BIGINT NOT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  UNIQUE KEY aperture_play_slate_user_thesis_date_window_unique (user_id, canonical_thesis_id, session_date_et, window_key),
  KEY aperture_play_slate_user_capture_idx (user_id, captured_at)
);

CREATE TABLE aperture_play_slate_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  slate_id INT NOT NULL,
  source_run_id INT NOT NULL,
  source_candidate_id INT NOT NULL,
  symbol VARCHAR(24) NOT NULL,
  condition_key VARCHAR(160) NOT NULL,
  recommendation_snapshot JSON NOT NULL,
  operator_decision ENUM('not_recorded', 'selected', 'skipped', 'deferred') NOT NULL DEFAULT 'not_recorded',
  operator_reason TEXT NULL,
  decided_at BIGINT NULL,
  outcome_status ENUM('pending', 'resolved', 'unavailable') NOT NULL DEFAULT 'pending',
  outcome_result ENUM('win', 'breakeven', 'loss', 'not_triggered', 'unresolved') NOT NULL DEFAULT 'unresolved',
  trigger_observation ENUM('met', 'not_met', 'not_observed') NOT NULL DEFAULT 'not_observed',
  exit_observation ENUM('time_stop', 'stop_hit', 'ambiguous', 'not_observed') NOT NULL DEFAULT 'not_observed',
  entry_price_cents BIGINT NULL,
  settlement_price_cents BIGINT NULL,
  return_bps INT NULL,
  r_multiple FLOAT NULL,
  outcome_basis ENUM('verified', 'modeled', 'unknown') NOT NULL DEFAULT 'unknown',
  outcome_provider_id VARCHAR(32) NULL,
  outcome_source_url TEXT NULL,
  observed_at BIGINT NULL,
  outcome_explanation TEXT NULL,
  computed_at BIGINT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  UNIQUE KEY aperture_play_slate_item_unique (slate_id, source_candidate_id),
  KEY aperture_play_slate_item_slate_idx (slate_id),
  KEY aperture_play_slate_item_condition_idx (condition_key, outcome_status, outcome_basis)
);
